# Generated by Django 4.2.2 on 2023-06-30 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_technology_technology_technologies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Technology',
            new_name='Technologies',
        ),
    ]
