# Generated by Django 4.2.2 on 2023-06-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_technology_technologies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Technologies',
            new_name='Technology',
        ),
    ]
