# Generated by Django 4.2.2 on 2023-06-30 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_technologies_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='creationDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
