# Generated by Django 4.2.2 on 2023-07-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_education_language_link_skill_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='school',
            field=models.CharField(max_length=40),
        ),
    ]
