# Generated by Django 4.2.2 on 2023-07-01 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_education_school'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Languages',
        ),
    ]
