# Generated by Django 4.2.2 on 2023-07-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_delete_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('stop_date', models.DateField()),
                ('duration', models.DurationField(blank=True, null=True)),
            ],
        ),
    ]
